version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.24.0
    ports:
      - "7233:7233"  # Temporal gRPC
      - "8233:8233"  # Temporal Web UI
    environment:
      - DB=postgres
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=admin
      - POSTGRES_SEEDS=host.docker.internal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - SKIP_SCHEMA_SETUP=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "workflow", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
